version: "3"

services:
  # nginx web server at front end
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - web_nw

  # web frontend, calls api
  web:
    build: web_frontend
    ports:
      - "8000:8000"
    volumes:
      - "./web_frontend/public/:/public/"
    depends_on:
      - redis
    networks:
      - web_nw

  # api backing web frontend, calls redis, rng, hash
  api:
    build: api
    stdin_open: true
    tty: true
    networks:
      - service_nw

  # produces a random number
  rng_service:
    build: rng_service
    ports:
      - "8001:80"
    networks:
      - service_nw

  # produces a SHA hash
  hash_service:
    build: hash_service
    ports:
      - "8002:80"
    networks:
      - service_nw

  # caching layer stores results
  redis:
    image: redis
    networks:
      - web_nw
      - service_nw

# service network for backend services
# web network for proxy + frontend
# redis caching layer bridges networks
networks:
  service_nw:
    driver: bridge
  web_nw:
    driver: bridge