apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rng
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: rng
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
